name: scf-knn
channels:
- conda-forge
- defaults
dependencies:
- python=3.8 
- pandas=1.2.3
- torchmetrics=0.9.3
- pip=22.2.2
- pip:
  - neptune-client==0.16.13
  - tqdm==4.64.1
  - numpy==1.24.1
  - scikit-learn==1.2.2
  - scipy==1.10.0
  - torch==1.8.0
  - torchvision==0.9.0
  - matplotlib==3.6.2